CC := gcc
CONNECT:= -pthread

unname_sem:unname_sem.c
	-$(CC) $^ -o $@ -Wall $(CONNECT)
	./$@
	-rm -f $@

unname_sem2:unname_sem2.c
	-$(CC) $^ -o $@ -Wall $(CONNECT)
	./$@
	-rm -f $@

unname_sem3:unname_sem3.c
	-$(CC) $^ -o $@ -Wall $(CONNECT)
	./$@
	-rm -f $@

	
unname_sem4:unname_sem4.c
	-$(CC) $^ -o $@ -Wall $(CONNECT)
	./$@
	-rm -f $@